name: Build final document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: antiemes/latex:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Compiling LaTeX document...'
      - run: make 
      - run: echo 'Storing artifact...'
      - uses: actions/upload-artifact@v1
        with:
          name: Final document
          path: hajnal-sisy2022-bolus.pdf

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: "hajnal-sisy2022-bolus.pdf"
          folderId: ${{ secrets.FOLDERID }}
          name: "hajnal-sisy2022-bolus.pdf" # optional string
          overwrite: "true" # optional boolean


#      - run: mkdir -p ~/.ssh
#      - run: ssh-keyscan -T 60 -H ${{ secrets.SSH_HOST_BOLUS }} >> ~/.ssh/known_hosts
#      - uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY_BOLUS }} 
#          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

